/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
//importing pakages...
import Login.welcome;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class update extends javax.swing.JFrame {
    //creating a method (filepath) to store user credentials 
    private static final String filepath3 = "E:\\Downloads\\Login\\src\\Login\\users.json";

    public update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton home = new javax.swing.JButton();
        javax.swing.JButton save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 431));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(106, 156, 137));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        home.setBackground(new java.awt.Color(255, 218, 179));
        home.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(102, 102, 102));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(255, 218, 179));
        save.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        save.setForeground(new java.awt.Color(102, 102, 102));
        save.setText("Save changes");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(193, 216, 195));
        table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Passsword"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/logo-white-1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(save)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(save)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //this home button will fire up back to welcome window
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        //initializing new identifier for welcome
        welcome wel = new welcome();
        wel.setLocationRelativeTo(null);//this method is use to maintain the window at the center of the screen while ruuning
        wel.setVisible(true);//visibility is true
        this.dispose();//close the program after it go to another window
    }//GEN-LAST:event_homeActionPerformed
    //this save button will save the input from the user
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        saveJsonData(filepath3);//saving the input to method 'saveJsonData' casting the filepath
        //it helps the user to know what's happening to the program
        JOptionPane.showMessageDialog(this, "Changes saved successfully.", "Save", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveActionPerformed
    //this method fuction to load the json file or data inside the table when the program started
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       /*incase of any error the reloading of json data is in try and catch to avoid
        crashing the whole program
        */
        try {
            loadJsonData();//calling the loadJsonData method
        } catch (ParseException ex) {
            Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened
    // this method helps to stored/saved the json data when the program is closed so the data won't loss
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        saveJsonData(filepath3);//method with casting the another method specifically filepath3 
    }//GEN-LAST:event_formWindowClosing
    //this method loads the user data from the json file and then it will display in the table 
    private void loadJsonData() throws ParseException {
        JSONParser parser = new JSONParser();//creating a json parser object

        try (FileReader reader = new FileReader(filepath3)) {//this line will trying to oopen the json file
            Object obj = parser.parse(reader);//parsing the json file and storing to object
            if (obj instanceof JSONObject) {
                JSONObject jsonObject = (JSONObject) obj;//casting the object (parsed obj) to JSONObject
                JSONArray usersArray = (JSONArray) jsonObject.get("users");//getting or extracting the "users" (users from the json) array
                DefaultTableModel model = (DefaultTableModel) table.getModel();// from line 181 to 182 this will get the table or jtable and clear existing data 
                model.setRowCount(0);
                
                if (usersArray != null) {//checking if the array is not null or empty or if the user exsist it will repeat  through each user object
                    for (Object userObj : usersArray) {// this will recaping the user object
                        JSONObject userObject = (JSONObject) userObj; // store the user and password to this jsonObj
                        String user = (String) userObject.get("user");//extracting the user from the json
                        String password = (String) userObject.get("password");//this also extracting the password from the json
                        model.addRow(new Object[]{user, password});// this will add another row to the table

                    }
                }
            }
            //error handling to avoid crashing the whole program
        } catch (IOException e) {
            System.err.println("Error loading JSON data: " + e.getMessage());//error handing message
        }
    }
    //this method will save the edited/table data back to the jsonfile (filepath3)
    private void saveJsonData(String filepath3) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();//grabbing or getting the table model
        JSONArray usersArray = new JSONArray();//naghimo ko ug json array to store user data
        for (int i = 0; i < model.getRowCount(); i++) {//this row will loop sa mga table rows
            JSONObject userObject = new JSONObject();//this row is use to store each row into obj
            userObject.put("user", model.getValueAt(i, 0));//diri ang function niya is to stored username/user back to json file
            userObject.put("password", model.getValueAt(i, 1));//also diri i will stored the passowrd abck to json file
            usersArray.add(userObject);//kani is to add new obj to json array
        }
        JSONObject jsonObject = new JSONObject();//kani kay bura ni syag main json obj nako 
        jsonObject.put("users", usersArray);//kani is to add user array directly to json obj
        //I surrounded the savinig process with try and catch to avoid crashing the system/program and handles errors 
        try (FileWriter file = new FileWriter(filepath3)) {//diri i created a new identifier for FileWriter specifically 'file' and open json file with the use of file identifier
            file.write(jsonObject.toJSONString());//diri is simply gina overrride niya ang data sa json sa file identifier it's more sounds like gina edit
            file.flush();//this method is used to clear/flush data to file, neither accepts any parameter nor returns any value
        } catch (IOException e) {
            System.err.println("Error saving JSON data: " + e.getMessage());// error handling message
        }
    }
    //this method makes the windows visible 
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
